### ISSUE TITLE
宿主中如何使用插件中的类

### ISSUE THREAD

**Issue by cubemoon** [iqiyi/Neptune#11]
如题，宿主中如何使用插件中的类

**Comment by zjupure** [comment]
宿主和插件应该是解耦独立的，什么场景下宿主需要依赖插件里的类

**Comment by cubemoon** [comment]
比如app有两个内嵌插件 A和B，宿主根据内部情况判断是加载显示A中的某个View还是B中的某个View

**Comment by zjupure** [comment]
宿主和插件是独立编译打包的，插件是运行在宿主环境中且支持动态更新，插件编译可以依赖宿主的代码，但是宿主不应该反向依赖插件，因为宿主一旦上线之后代码就固定不可变了，而插件可以随时发布更新。建议宿主和插件的边界是Activity，宿主根据不同的场景，选择跳转A插件还是B插件的页面。

如果需要在宿主的Activity页面中加载插件的Fragment或者View，目前框架也是支持的，这种场景下需要指定插件的Fragment或者View的类名，通过反射创建，而不是通过编译依赖插件的代码形式，这样要求插件需要keep主被宿主引用的Fragment或者View的类名。可以看`PluginManager#createFragment()`和`PluginManager#createView()`两个API，创建出插件的Fragment或者View之后，可以动态添加到宿主Activity中。

不建议宿主直接加载加载插件中的普通类，因为这些在多团队开发中，插件中类的变更对于宿主而言都是不可预期的，这些操作可以通过接口实现或者注入的方式实现，比如在宿主中定义好抽象接口，插件实现不同的实例注入到宿主，宿主在运行期根据插件的加载情况和业务需求，选择执行不同的实现类。

**Comment by cubemoon** [comment]
那就是没法实现比如 一个插件作为公共基类和基础库包，供宿主和其他插件调用的方式了吧。

**Comment by zjupure** [comment]
插件作为公共基类和基础库包，给宿主依赖动态加载，这样做的目的是什么呢，为了热更新？基础库性质的代码应该打入宿主apk，如果做成动态化，没法确定调用业务的时机和界限，一旦插件在某些机型上加载失败了，会影响宿主APP整体的运行。宿主代码之外，如果有多个业务插件需要依赖一些基础能力，是可以单独抽离成基础插件，供多个业务插件编译依赖的，只需要管理好插件依赖即可。
所以宿主必要的基础功能或者核心功能，做成动态插件让宿主反向依赖，目的和要解决的痛点是什么？做成内置插件和代码直接打入apk，有什么差异和风险，这点需要想清楚。

**Comment by cubemoon** [comment]
明白了。

**Comment by zhoujianhanyu** [comment]
我这边使用插件的目的是随时都可以更新某个功能。做法就是：发版本的时候会带上当前最新的插件（把插件的代码也编译到 apk 包），当有插件需要更新的时候就下发插件包，宿主会根据插件的版本号来加载插件里的类。假如插件加载失败了，还可以加载 apk 包里的插件代码。也许这样的方案会适合你的需求 @cubemoon

**Comment by cubemoon** [comment]
@zhoujianhanyu 是怎么加载插件中的类的呀。能给段示例代码吗

**Comment by zhoujianhanyu** [comment]
通过插件 apk 的路径 new 一个 DexClassLoader ，用这个 DexClassLoader 对象 loadClass 方法加载插件里的类 @cubemoon

**Comment by cubemoon** [comment]
@zhoujianhanyu  3QU。明白了
