### ISSUE TITLE
plug 调用getPackageName获取到的是宿主包名

### ISSUE THREAD

**Issue by hzx0910** [iqiyi/Neptune#15]

**Comment by zjupure** [comment]
是的，这个方法重写会有很多副作用，插件需要获取自己的包名可以通过`ContextUtils#getPluginPackageName()`工具方法获取

**Comment by hzx0910** [comment]
但是plugin调用的三方库如果用到getPackageName就不能正常使用了，比如contentprovider authority包含插件包名

**Comment by zjupure** [comment]
@hzx0910 接入三方库时，最终还是运行在宿主里，使用宿主的包名去申请token， appid等信息。contentprovider的authority也换成宿主APP的包名即可
