### ISSUE TITLE
插件中的meta数据，当插件启动的时候，是读取不到的？

### ISSUE THREAD

**Issue by blueway** [iqiyi/Neptune#2]
插件中的meta数据，当插件启动的时候，插件是读取不到这些配置数据的？

**Comment by zjupure** [comment]
由于部分第三方SDK会获取ApplicationInfo里packageName作为应用包名，去统计应用的日活及做一些校验，如果重写了Context的getApplicationInfo方法，会导致宿主和插件在运行时被这些第三方SDK当做两个APP，有一定的影响，所以目前没有重写Context的getApplicationInfo方法，即不能直接通过Context获取ApplicationInfo及meta数据。后面考虑提供工具方法获取插件的ApplicationInfo数据。

**Comment by zjupure** [comment]
release 2.6.0 to support this feature
