### ISSUE TITLE
Android 5.1,Flyme 6.3.0.0Q  launchPlugin fail

### ISSUE THREAD

**Issue by hamiltonhzy** [iqiyi/Neptune#3]
09-29 19:48:12.999 26801-26801/com.iqiyi.host.sample I/runtime_plugin: [ ComponentFinder ] : matchServiceProxyByFeature:org.qiyi.pluginlibrary.component.ServiceProxy1
09-29 19:48:14.211 26801-26846/com.iqiyi.host.sample I/general_plugin: [ PluginPackageManager ] : setActionFinishCallback with process name: com.iqiyi.host.sample:plugin1
09-29 19:48:14.212 26801-26822/com.iqiyi.host.sample I/install_plugin: [ PluginPackageManager ] : packageAction , com.iqiyi.plugin.sample installed : true installing: false
09-29 19:48:14.214 26801-26823/com.iqiyi.host.sample I/general_plugin: [ PluginPackageManager ] : getPackageInfo com.iqiyi.plugin.sample return null due to sPluginInfoProvider is null
09-29 19:48:14.216 26801-26846/com.iqiyi.host.sample I/general_plugin: [ PluginPackageManager ] : getPackageInfo com.iqiyi.plugin.sample return null due to sPluginInfoProvider is null
09-29 19:48:14.216 26801-26822/com.iqiyi.host.sample I/runtime_plugin: [ PluginPackageManager ] : getPackageInfo from local cache

**Comment by zjupure** [comment]
可以断点看下这个方法PluginPackageManager.getPackageInfo()为什么没有返回有效的值？

**Comment by zjupure** [comment]
fix in 2.7.0 release, if still have problem, please reopen it.
