### ISSUE TITLE
关于插件加载成功,无法生效问题(内附临时解决方法).

### ISSUE THREAD

**Issue by quietUncle** [iqiyi/Neptune#7]
看了一下代码,插件的信息是通过PluginPackageManagerService 来管理的.
在PluginPackageManagerNative的getInstance(context)方法里面和PluginPackageManagerService进行了绑定.

启动一个插件是通过PluginManager的launchPlugin执行的.
在里面调用了
PluginPackageManagerNative.getInstance(mHostContext.getApplicationContext())
                .getPackageInfo(packageName);
等方法.
经过调试发现,这个时候是第一次调用getInstance(),这个时候顺序执行下去,service是没被绑定的.
导致.getPackageInfo返回的是null.

我这临时解决的办法是在

PluginPackageManagerNative.getInstance(mHostContext.getApplicationContext())
                .getPackageInfo(packageName);
之前先调用了PluginPackageManagerNative.getInstance(),然后等待了50毫秒.

        PluginManager.java     ->   launchPlugin()
    

        PluginPackageManagerNative.getInstance(mHostContext.getApplicationContext());

        SystemClock.sleep(50);

        final PluginLiteInfo info = PluginPackageManagerNative.getInstance(mHostContext.getApplicationContext())
                .getPackageInfo(packageName);

这样可以暂时解决问题,让demo跑起来.
理论上应该找到一个合适的时机去进行绑定的.

**Comment by zjupure** [comment]
在进程启动的时候，Neptune SDK初始化就会调用PluginPackageManagerNative.getInstance(context)方法尝试绑定到主进程的PluginPackageManagerService,。在launchPlugin()时，由于bindService()的异步行为，可能会导致执行到launchPlugin()时Service还没有connect成功。但是在PluginPackageManagerNative.getInstance(mHostContext.getApplicationContext())
.getPackageInfo(packageName)的方法实现里，Service如果没有connect，则会从当前进程维护的已安装插件信息里查询，获取到的PackageInfo还是为null，说明还是PluginPackageManager在恢复已安装插件列表信息时的异步操作还是太慢了。
后面考虑下针对Service未bind的场景，采用其他更可靠的IPC方式获取信息。

**Comment by quietUncle** [comment]
@zjupure 
访问插件信息都是通过PluginPackageManagerNative来执行的,而PluginPackageManagerNative必须要与PluginPackageManagerService连接上才能有用.
那么可不可以考虑提供一个类似doOnServiceConnect的方法呢.
将launch最后要执行的操作封装成一个pendingaction,等待PluginPackageManagerNative来调用.
我看PluginPackageManagerNative里面插件安装卸载已经采用了这种模式.
那么luanch可不可以也同样采用?


在PluginPackageManagerNative加了类似的代码,同样也可以达到目的.

      private Action0 pendingIntentAction;//

      public void intentAction(Action0 action0) {
        if (isConnected()) {
            PluginDebugLog.log(TAG, "the service already connect ,just call");
            action0.call();
           } else {
            PluginDebugLog.log(TAG, "the service disconnected ,wait it connect");
            this.pendingIntentAction = action0;
          }
      }

    public void onServiceConnected(ComponentName name, IBinder service) {
                     ....
                    if (pendingIntentAction != null) {
                        PluginDebugLog.runtimeLog(TAG, "onServiceConnected call last pendingIntentAction");
                        pendingIntentAction.call();
                        pendingIntentAction = null;
                    }

**Comment by zjupure** [comment]
多谢你的建议，我们评估验证一下

**Comment by zjupure** [comment]
使用ContentProvider sync操作优化了Service未bind的场景，代码已push更新。
