### ISSUE TITLE
插件之间如何进行主件跳转？

### ISSUE THREAD

**Issue by blueangle** [iqiyi/Neptune#8]
在Plugin_1的Plugin_1_MainActivity中通过以下方式，希望跳转到Plugin_2中的Plugin_2_TestActivity，但是，无法完成跳转，为什么？
Intent intent = new Intent();
 ComponentName cn = new ComponentName("com.iqiyi.plugin.sample_2", "com.iqiyi.plugin.sample.Plugin_2_TestActivity");  //
// 启动默认入口Activity
intent.setComponent(cn);
startActivity(intent);

**Comment by zjupure** [comment]
这个没有支持，如果对方插件还没有load进内存，则需要在startActivity方法里加载容易造成跳转时卡顿，需要跳转到其他插件时可以使用Neptune的公开API  launchPlugin(context， intent)，传入对应插件的intent异步化处理。
